### ISSUE TITLE
Color not looking as expected

### ISSUE THREAD

**Issue by mauri-peya** [primer/prism#29]
When using HSL values from my colors in Figma inside Primer Prism, the resulting color is not what is supossed to be, am I missing something?
<img width="1056" alt="Captura de Pantalla 2022-06-17 a la(s) 21 05 56" src="https://user-images.githubusercontent.com/94491625/174414194-95d6e3b6-4d78-4ac2-8e31-20b229cf14e4.png">
<img width="295" alt="Captura de Pantalla 2022-06-17 a la(s) 21 06 08" src="https://user-images.githubusercontent.com/94491625/174414232-3d24d526-1218-4534-8a80-008d80ce6975.png">

**Comment by colebemis** [comment]
👋 Hi, @mauri-peya. Primer Prism uses the [HSLuv](https://www.hsluv.org) which is slightly different than the color space that Figma uses. Here's a more detailed explanation: https://www.hsluv.org/comparison/

You can use the [HSLuv](https://www.hsluv.org/) website to convert a hex color from Figma to the HSLuv color space:

![CleanShot 2022-06-18 at 19 03 40](https://user-images.githubusercontent.com/4608155/174462845-919982be-eda8-43e2-9800-4c272fb97a27.png)

**Comment by mauri-peya** [comment]
Oh! Didn't know about that, thanks for the clarification!
