### ISSUE TITLE
App crashes when an empty scale is opened

### ISSUE THREAD

**Issue by rafaeltab** [primer/prism#45]
**Describe the bug**
App crashes when an empty scale is opened

**To Reproduce**
1. Create a new palette
2. Import the following JSON
```jsonc
{
  "lightgrey": [],
  "dimgrey": [],
  "olivedrab": "#6b8e23"
}
```
3. select either the `lightgrey` or `dimgrey` scales

**Expected behavior**
An empty scale should be displayed, it should allow adding a color using the `+` button. 
Optionally, the pane on the right could continue to function but without displaying any color settings, just the scale settings.

P.S. Sorry for not making this issue earlier

**Comment by pavelkeyzik** [comment]
I'll take it 😊

**Comment by pavelkeyzik** [comment]
Hey @rafaeltab it should be fixed. Now you wouldn't be able to import something with empty scale 😊 If you're happy with the result, please, close the issue
